import type { Control, ExplainerSpec } from '#lib/explainer/index.ts';

const degree: Control = {
	type: 'range',
	id: 'degree',
	label: 'Flexibility (degree of the curve)',
	min: 0,
	max: 12,
	step: 1,
	default: 3,
	format: (v) =>
		v === 0
			? '0: a flat line'
			: v === 1
				? '1: a straight line'
				: v === 2
					? '2: one bend'
					: `${v}: up to ${v - 1} bends`,
	help: 'How many ups and downs the model is allowed.'
};

const count: Control = {
	type: 'range',
	id: 'count',
	label: 'Number of examples',
	min: 8,
	max: 80,
	step: 1,
	default: 21
};

const noise: Control = {
	type: 'range',
	id: 'noise',
	label: 'Noise in the examples',
	min: 0,
	max: 0.4,
	step: 0.01,
	default: 0.15,
	format: (v) => (v === 0 ? 'none' : v.toFixed(2))
};

const truth: Control = {
	type: 'toggle',
	id: 'truth',
	label: 'Show the true curve',
	default: false,
	help: 'The rule the examples were generated from, which a real learner never gets to see.'
};

const fresh: Control = {
	type: 'action',
	id: 'fresh',
	label: 'New examples',
	action: 'New examples',
	help: 'Draw a new random set of examples from the same rule.'
};

export const spec: ExplainerSpec = {
	slug: 'learning-from-data',
	title: 'How machines learn from examples',
	summary:
		'Fit curves to points you can drag, then hold some points back and discover why a model that fits its examples perfectly can predict new ones worse.',
	chapters: [
		{ id: 'fit', title: 'Fitting a model' },
		{ id: 'flex', title: 'How flexible?' },
		{ id: 'test', title: 'Testing on new examples' }
	],
	steps: [
		// ------------------------------------------------------------------ fit
		{
			id: 'examples',
			chapter: 'fit',
			title: 'Learning from examples',
			scene: 'fit',
			hints: { phase: 'points' },
			duration: 16,
			controls: [fresh],
			body: `
<p>Much of what is called machine learning is this: given <strong>examples</strong> of inputs and the outputs that went with them, find a rule that predicts the output for an input it has not seen.</p>
<p>Each dot is one example: an input along the bottom (<i>x</i>) and the measured output up the side (<i>y</i>) — think of the temperature on a day and how much a plant grew, or the size of a house and its price. The examples follow a pattern, but each one is a little off: measurements are noisy.</p>
<p>The examples on this page are generated by the computer from a hidden rule plus random noise, so that we can check later how well the learning went.</p>`
		},
		{
			id: 'line',
			chapter: 'fit',
			title: 'A model: the best straight line',
			scene: 'fit',
			hints: { phase: 'line' },
			duration: 18,
			controls: [fresh],
			body: `
<p>The simplest rule is a straight line: output = <i>a</i> × input + <i>b</i>. This is a <dfn data-def="A rule with adjustable settings (parameters) that turns an input into a predicted output.">model</dfn> with two settings, the slope <i>a</i> and the height <i>b</i>. <strong>Learning</strong> means choosing the settings that fit the examples best.</p>
<p>Drag any dot and watch the line follow: the computer re-fits it instantly. Pull one dot far away and see how much a single odd example can tilt the line.</p>`
		},
		{
			id: 'error',
			chapter: 'fit',
			title: 'Measuring how wrong it is',
			scene: 'fit',
			hints: { phase: 'error' },
			duration: 18,
			controls: [fresh],
			body: `
<p>“Best” needs a number. For each example, the gap between the dot and the line is the model's <strong>error</strong> on it. Square each gap — so that misses above and below both count, and big misses count a lot — and average them. That is the <dfn data-def="The average of the squared differences between a model's predictions and the true outputs.">mean squared error</dfn>.</p>
<p>The squares drawn on the gaps are exactly those numbers. The best line is the one that makes their average as small as possible — the <dfn data-def="Choosing a model's settings to minimise the sum of squared errors; for a straight line there is an exact formula.">least-squares</dfn> fit, a method used since Gauss and Legendre around 1800.</p>`
		},
		// ------------------------------------------------------------------ flex
		{
			id: 'flexible',
			chapter: 'flex',
			title: 'More flexible models',
			scene: 'fit',
			hints: { phase: 'degree' },
			duration: 20,
			controls: [degree, fresh],
			body: `
<p>A straight line cannot follow a curved pattern. Give the model more settings and it can bend: a <dfn data-def="A curve made of powers of x: a + b·x + c·x² + …; its degree is the highest power. A degree-d polynomial can turn d − 1 times.">polynomial</dfn> of degree 2 can bend once, degree 3 twice, and so on.</p>
<p>Slide the flexibility up. The training error — measured on the examples the model was fitted to — always goes down: a more flexible curve can always get at least as close to the dots.</p>
<p>So should we just use the most flexible model we can?</p>`
		},
		{
			id: 'overfit',
			chapter: 'flex',
			title: 'Too flexible: fitting the noise',
			scene: 'fit',
			hints: { phase: 'overfit' },
			duration: 20,
			controls: [degree, truth, fresh],
			body: `
<p>Push the flexibility to the top. The curve now wiggles through nearly every dot, and the training error is almost zero. But look between the dots: it swings wildly, making predictions no sensible person would make.</p>
<p>The model has learned the <em>noise</em> — the random wobble of these particular examples — instead of the pattern behind them. This is <dfn data-def="When a model fits the noise in its training examples and so predicts new cases worse.">overfitting</dfn>. Turn on the true curve to see what the model should have found.</p>
<p>Too little flexibility is a problem too: a straight line through a curved pattern <em>underfits</em>, missing the pattern itself.</p>`
		},
		// ------------------------------------------------------------------ test
		{
			id: 'test',
			chapter: 'test',
			title: 'Keep some examples back',
			scene: 'fit',
			hints: { phase: 'test' },
			duration: 20,
			controls: [degree, fresh],
			body: `
<p>A real learner never sees the true curve. So how can we tell a good fit from an overfit one? <strong>Hold some examples back.</strong></p>
<p>The hollow dots are a <dfn data-def="Examples kept aside and not used for fitting, used only to measure how well the model predicts new cases.">test set</dfn>: the model is fitted to the solid dots only, then asked to predict the hollow ones it has never seen. Its error on them — the <strong>test error</strong> — is an honest measure of how well it will do on new cases.</p>
<p>Slide the flexibility again and watch the two numbers. Training error keeps falling. Test error falls at first, then turns upward.</p>`
		},
		{
			id: 'sweetspot',
			chapter: 'test',
			title: 'The sweet spot',
			scene: 'curve',
			hints: { phase: 'curve' },
			duration: 22,
			controls: [degree, fresh],
			body: `
<p>Plot both errors against flexibility and the story is plain. Training error only ever goes down. Test error makes a U: too stiff on the left, overfitting on the right, and a <strong>sweet spot</strong> in between — the model that predicts new cases best.</p>
<p>This is how flexibility is chosen in practice, from simple fits like this one to neural networks with billions of settings: never by the training error, always by error on examples held back.</p>`,
			notes: `<p>With few examples, which ones happen to land in the test set matters a lot: try <em>New examples</em> a few times and the sweet spot moves. Practitioners therefore repeat the split several ways and average (cross-validation). And once a test set has been used to choose the model, its error is a little optimistic — so a final, untouched set is kept for the very end.</p>`
		},
		{
			id: 'moredata',
			chapter: 'test',
			title: 'More examples, less overfitting',
			scene: 'curve',
			hints: { phase: 'data' },
			duration: 22,
			controls: [count, noise, degree, fresh],
			body: `
<p>Overfitting happens when a model has more freedom than its examples can pin down. Add examples and each wiggle of a flexible curve has to agree with more dots, so the noise averages out: the sweet spot moves to the right and the test error drops.</p>
<p>Make the examples noisier and the opposite happens: there is more noise to mistake for pattern, so a simpler model wins.</p>
<p>That is the heart of learning from data: <strong>fit the examples, but only as closely as the amount and quality of the data justify</strong> — and judge the result on examples the model has never seen.</p>`
		}
	]
};
